### PR TITLE
Introduce iterator traits

### PR DESCRIPTION
**Pull request by Flamefire**
This makes it possible to use the iterator with most stl algorithm. I used it e.g. with std::distance which is quite handy.

Make sure this compiles correctly, please as I only tested it in VS

### CODE REVIEW

**Comment by satoren** [comment]
Thank you for PR.
I want to change to random_access_iterator.
std::distance(O(1)) need random_access_iterator, Otherwise O(N).

**Comment by Flamefire** [comment]
I left it as forward_iterator to avoid having to define the remaining functions. This already helps a lot and making it random_access would "only" get you a speedup. As the code gets larger you might want to put the whole VarArgs class into a new file to not clutter that to much.
Also: You normally don't have many arguments. So the `N` is pretty small here.

**Comment by satoren** [comment]
I tried to implement
0089fbc48cc729d35b5e49729932fd7f36ba21fb

**Comment by Flamefire** [comment]
Looks good :+1: 
Only thing: Using std::iterator is deprecated in C++17 which is why I removed it in my last commit. So better define those types explicitely. It might also be a good idea, to rename your `reference` a I did or define it IN the iterator, so you don't have `typedef reference reference` ;) I think you don't need the value_type/reference definition in the container itself.

**Comment by satoren** [comment]
Thank you for advice.

**Pull request closed without merging**
