### PR TITLE
Use pedantic and remove extra commas

### PR DESCRIPTION
**Pull request by Flamefire**
New version of kaguya does not compile with pedantic enabled (some compilers ignore `-isystem`, so this is a show stopper)

This adds `-pedantic` `-Werror` to detect these errors in the test suite and fixes double-comma errors (after macros)

### CODE REVIEW

**Comment by satoren** [comment]
gcc-4.4 + lua-5.3.3 + C++03
```
lua-5.3.3/src/lua.h:96: error: ISO C++ 1998 does not support ‘long long’
```

**Comment by Flamefire** [comment]
Working on it...

**Comment by Flamefire** [comment]
@satoren Ok, travis and appveyor build, locally I don't see problems with g++ and clang. Seems Jenkins still has some failures but I can't get access to the build log. Could you tell me what is left?

**Comment by satoren** [comment]
clang-3.8 + lua-5.3.3 + C++03
```
include/kaguya/native_function.hpp:740:3: error: unused typedef 'boost_static_assert_typedef_740' [-Werror,-Wunused-local-typedef]
```

**Comment by Flamefire** [comment]
Ok, next? :)

**Comment by satoren** [comment]
clang-3.8
```
/var/lib/jenkins/workspace/satoren/kaguya/PR-47/include/kaguya/utility.hpp:247:5: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
/var/lib/jenkins/workspace/satoren/kaguya/PR-47/include/kaguya/config.hpp:85:58: note: expanded from macro 'KAGUYA_USE_CXX_ABI_DEMANGLE'
#define KAGUYA_USE_CXX_ABI_DEMANGLE defined(__GNUC__) || defined(__clang__)
```

**Comment by Flamefire** [comment]
Finally... :)

**Comment by satoren** [comment]
Thank you for your hard work :smile:

**Pull request merged**
