### PR TITLE
code format by clang-format

### PR DESCRIPTION
**Pull request by satoren**

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Not really a fan of it not indenting code inside macro `#if` blocks, any way to fix that?  >.>

**Comment by satoren** [comment]
That is not indenting inside #if blocks. what are you talking about?

**Comment by OvermindDL1** [comment]
> That is not indenting inside #if blocks. what are you talking about?

Correct, but shouldn't it be identing inside `#if` blocks to make it easy to see the scope of the macro at a glance?

**Comment by satoren** [comment]
Can you write code example and clang-format option?
I do not have a strong policy on coding style. but I do not want manual indenting.

**Pull request merged**
