### PR TITLE
Add external property getter and setter function.

### PR DESCRIPTION
**Pull request by aster2013**

### CODE REVIEW

**Comment by satoren** [comment]
Could you write a test?

**Comment by aster2013** [comment]
In Urho3D I add following property functions:

```
/// @brief add member property with getter function.(read only property, experimental)
template<typename GetType>
UserdataMetatable& addProperty(const char* name, GetType(class_type::*getter)()const);

/// @brief add member property with setter function.(write only property, experimental)
template<typename SetType, typename SetRetType>
UserdataMetatable& addProperty(const char* name, SetRetType(class_type::*setter)(SetType));

/// @brief add member property with setter, getter functions.(read write property, experimental)
template<typename GetType, typename SetType, typename SetRetType>
UserdataMetatable& addProperty(const char* name, GetType(class_type::*getter)()const, SetRetType (class_type::*setter)(SetType));

//----------------------------------------------------------------------------------------------------------------

/// @brief add member property with external getter function.(read only property, experimental)
template<typename GetType>
UserdataMetatable& addProperty(const char* name, GetType(*getter)(const class_type*));

/// @brief add member property with external setter function.(write only property, experimental)
template<typename SetType, typename SetRetType>
UserdataMetatable& addProperty(const char* name, SetRetType(*setter)(class_type*, SetType));

/// @brief add member property with external setter, getter functions.(read write property, experimental)
template<typename GetType, typename SetType, typename SetRetType>
UserdataMetatable& addProperty(const char* name, GetType(*getter)(const class_type*), SetRetType(*setter)(class_type*, SetType));
```

**Comment by satoren** [comment]
It is can not receive setter result in Lua. For what?

**Comment by aster2013** [comment]
The reason is these is some function in Urho3D like:
```
bool SetModel(Model* model);
Model* GetModel() const
```
The **SetModel** function will return true. but I want to use it as property setter. Just so...

**Pull request merged**
